spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  devtools: # optional, to ignore StorageClient in IDE hot-reload
    restart:
      exclude: 'storage/**'
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  web:
    cors:
      allowed-origins: '*'
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true
      max-age: 3600
server:
  port: 8080
jwt:
  secret: 2B4B6250655368566D597133743677397A24432646294A404E635266546A576E
  expiration: 86400000

storage:
  enabled: false
  bucket: items
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  region: us‑east‑1
