spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        format_sql: true
        show_sql: true
    show-sql: true
  devtools:
    restart:
      exclude: 'storage/**'
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  web:
    cors:
      allowed-origins: '*'
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true
      max-age: 3600
server:
  port: 8080
jwt:
  secret: 2B4B6250655368566D597133743677397A24432646294A404E635266546A576E
  expiration: 86400000
storage:
  enabled: true
  bucket: items
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  region: us‑east‑1
