spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
jwt:
  secret: 2B4B6250655368566D597133743677397A24432646294A404E635266546A576E
  expiration: 86400000